import {state,esc,button,logo,categories,registrationCarLabel,renderAvailabilityTimeline,crewColorClass,coversHour,pilotCount,canManage,api} from './core.mjs';
import {renderRegistration} from './registration.mjs';

function contentSummary(title,count){return `<summary class="ux-content-accordion-summary"><span class="ux-content-accordion-title">${esc(title)}</span><span class="ux-content-accordion-count">${count}</span><span class="ux-content-accordion-chevron" aria-hidden="true">›</span></summary>`;}
function statusPill(crew){return `<span class="crew-compact-status ${crew.locked?'is-complete':'is-open'}">${crew.locked?'ÉQUIPAGE COMPLET':'ÉQUIPAGE OUVERT'}</span>`;}
function coverage(event,departure,regs){const duration=event.durationHours||6;const counts=Array.from({length:duration},(_,i)=>regs.filter(reg=>coversHour(reg,i)).length);const covered=counts.filter(Boolean).length;return{duration,counts,covered,missing:Math.max(0,duration-covered)};}

function courseCrew(event,departure,crew,index){
  const regs=(crew.registrationIds||[]).map(id=>departure.availability.find(reg=>reg.id===id)).filter(Boolean); const cov=coverage(event,departure,regs); const names=regs.map(reg=>reg.name).join(' · ')||'Aucun pilote affecté'; const open=regs.some(reg=>reg.mine);
  const capacity=crew.locked?'<p class="crew-capacity-message is-complete">Équipage verrouillé</p>':cov.missing?`<p class="crew-capacity-message is-open needs-pilots">Il reste de la place dans cet équipage : ${cov.missing} h de course ${cov.missing>1?'ne sont':'n’est'} pas encore couverte${cov.missing>1?'s':''}.</p>`:'';
  return `<details class="crew-pilot-group crew-pilot-accordion ${crewColorClass(crew.id,index)} ${crew.locked?'is-complete':'is-open'}" data-crew-id="${crew.id}" data-crew-locked="${Boolean(crew.locked)}" data-crew-mine="${regs.some(reg=>reg.mine)}" data-crew-team="${esc(crew.name)}" ${open?'open':''}><summary class="crew-pilot-accordion-summary" aria-label="${esc(crew.name)} · ${esc(names)} · ${esc(crew.car||'Voiture à choisir')}"><span class="crew-compact-category" aria-hidden="true">${logo(crew.category)}</span><span class="crew-compact-team"><strong>${esc(crew.name)}</strong></span><span class="crew-compact-pilots">${esc(names)}</span><span class="crew-compact-car">${esc(crew.car||'Voiture à choisir')}</span>${statusPill(crew)}<span class="crew-compact-chevron" aria-hidden="true">›</span></summary><div class="crew-pilot-accordion-body" data-pilot-columns="${Math.max(1,Math.min(3,regs.length||1))}">${capacity}${regs.length?regs.map(reg=>renderRegistration(reg,departure,event.durationHours||6,false)).join(''):'<p class="empty">Aucun pilote affecté.</p>'}</div></details>`;
}

export function renderPilots(event,departure){
  const crews=[...(departure.crews||[])].sort((a,b)=>event.categories.indexOf(a.category)-event.categories.indexOf(b.category)||String(a.name).localeCompare(String(b.name),'fr',{sensitivity:'base',numeric:true})); const assigned=new Set(crews.flatMap(crew=>crew.registrationIds||[]));
  const unassigned=(departure.availability||[]).filter(reg=>reg.status!=='unavailable'&&!assigned.has(reg.id)).sort((a,b)=>event.categories.indexOf(a.category)-event.categories.indexOf(b.category)||String(a.name).localeCompare(String(b.name),'fr',{sensitivity:'base'})); const unavailable=(departure.availability||[]).filter(reg=>reg.status==='unavailable');
  const pilots=unassigned.length?`<section class="ux-unassigned-section"><div class="ux-unassigned-grid">${unassigned.map(reg=>renderRegistration(reg,departure,event.durationHours||6)).join('')}</div></section>`:`<section class="ux-unassigned-section"><p class="empty">${departure.availability.length?'Tous les pilotes disponibles sont déjà affectés à un équipage.':'Aucun pilote inscrit sur ce départ.'}</p></section>`;
  const unavailableHtml=unavailable.length?`<details class="ux-crew-bucket ux-unavailable-bucket"><summary><span>Pilotes indisponibles</span><strong>${unavailable.length}</strong></summary><div class="ux-crew-bucket-body">${unavailable.map(reg=>renderRegistration(reg,departure,event.durationHours||6)).join('')}</div></details>`:'';
  return `<div class="pilot-section"><div class="ux-course-overview ux-course-split-overview"><details class="ux-course-pilots-accordion">${contentSummary('Pilotes inscrits',unassigned.length)}<div class="ux-course-pilots-body">${pilots}${unavailableHtml}</div></details><details class="ux-course-crews-accordion">${contentSummary('Équipages',crews.length)}<div class="ux-course-crews-body">${crews.length?crews.map((crew,index)=>courseCrew(event,departure,crew,index)).join(''):'<p class="empty">Aucun équipage pour ce départ.</p>'}</div></details></div></div>`;
}

function stateControl(crew,departure){return `<div class="crew-state-control"><span class="crew-state-label"><span class="crew-state-lock" aria-hidden="true">${crew.locked?'🔒':'🔓'}</span><span>Équipage</span></span><label class="crew-state-select-wrap"><span class="sr-only">État de l’équipage</span><select class="crew-state-select" data-crew-state-select data-crew-id="${crew.id}" data-departure="${departure.id}" data-version="${crew.version}"><option value="open" ${crew.locked?'':'selected'}>Ouvert</option><option value="locked" ${crew.locked?'selected':''}>Équipage complet</option></select><span class="crew-state-chevron" aria-hidden="true">▾</span></label></div>`;}
function candidate(event,departure,crew,reg){return `<article class="ux-crew-candidate crew-candidate-action-card"><div class="crew-candidate-info"><span class="ux-candidate-head"><strong>${esc(reg.name)}</strong></span><small>${esc(registrationCarLabel(reg))}</small><small>Coéquipier souhaité : ${esc(reg.preferredPilot||'aucune préférence')}</small>${renderAvailabilityTimeline({departure,duration:event.durationHours||6,status:reg.status,label:`Disponibilités de ${reg.name}`})}</div>${button('add-crew-pilot','Ajouter',`data-id="${crew.id}" data-departure="${departure.id}" data-registration="${reg.id}" aria-label="Ajouter ${esc(reg.name)} à l’équipage"`,'primary-button crew-add-pilot-button')}</article>`;}
function remaining(event,departure,reg){return `<article class="pilot-row ux-remaining-pilot-card"><div class="pilot-main"><span class="pilot-name">${esc(reg.name)}</span><span class="pilot-category-logo">${logo(reg.category)}</span><span class="pilot-car">${esc(registrationCarLabel(reg))}</span>${reg.preferredPilot?`<span class="pilot-preference">Souhaite rouler avec : <strong>${esc(reg.preferredPilot)}</strong></span>`:''}</div>${renderAvailabilityTimeline({departure,duration:event.durationHours||6,status:reg.status,label:`Disponibilités de ${reg.name}`})}</article>`;}

function managementCard(event,departure,crew,index,unassigned,manage){
  const regs=(crew.registrationIds||[]).map(id=>departure.availability.find(reg=>reg.id===id)).filter(Boolean);const cov=coverage(event,departure,regs);const candidates=unassigned.filter(reg=>reg.category===crew.category);const names=regs.map(reg=>reg.name).join(' · ')||'Aucun pilote affecté';const open=state.crewManagementOpen.has(crew.id);
  return `<details class="crew-card crew-management-accordion crew-category-${categories[crew.category]?.css||''} ${crewColorClass(crew.id,index)} ${crew.locked?'is-complete':'is-open'}" data-crew="${crew.id}" data-crew-locked="${Boolean(crew.locked)}" data-crew-team="${esc(crew.name)}" ${open?'open':''}><summary class="crew-pilot-accordion-summary crew-management-summary" aria-label="${esc(crew.name)} · ${esc(names)} · ${esc(crew.car||'Voiture à choisir')}"><span class="crew-compact-category" aria-hidden="true">${logo(crew.category)}</span><span class="crew-compact-team"><strong>${esc(crew.name)}</strong></span><span class="crew-compact-pilots">${esc(names)}</span><span class="crew-compact-car"><span class="crew-compact-car-label">${esc(crew.car||'Voiture à choisir')}</span>${manage?button('edit-crew','Modifier',`data-id="${crew.id}" data-departure="${departure.id}"`,'secondary-button crew-summary-edit'):''}</span>${statusPill(crew)}<span class="crew-compact-chevron" aria-hidden="true">›</span></summary><div class="crew-management-accordion-body"><div class="crew-card-header"><div>${manage?stateControl(crew,departure):''}</div><span class="coverage-summary">${regs.length} pilote(s) · ${cov.covered}/${cov.duration} h</span></div><ul class="crew-roster">${regs.map(reg=>`<li><div><strong class="crew-pilot-name">${esc(reg.name)}</strong><small>${esc(registrationCarLabel(reg))}${reg.preferredPilot?` · souhaite ${esc(reg.preferredPilot)}`:''}</small></div>${manage&&!crew.locked?button('remove-crew-pilot','Retirer',`data-id="${crew.id}" data-departure="${departure.id}" data-registration="${reg.id}"`,'danger-button crew-member-action'):''}</li>`).join('')||'<li>Aucun pilote affecté.</li>'}</ul>${renderAvailabilityTimeline({departure,duration:cov.duration,counts:cov.counts,label:'Disponibilité de l’équipage'})}${cov.missing?`<p class="coverage-note">${cov.missing} heure(s) sans présence.</p>`:''}${manage&&!crew.locked?`<div class="ux-crew-candidate-wrap"><div class="ux-candidate-title"><strong>Pilotes disponibles · ${esc(crew.category)}</strong><span>Clique sur Ajouter pour affecter un pilote</span></div><div class="ux-crew-candidate-grid">${candidates.length?candidates.map(reg=>candidate(event,departure,crew,reg)).join(''):'<p class="empty">Aucun pilote à affecter dans cette catégorie.</p>'}</div></div>`:''}${manage?`<div class="crew-actions">${button('delete-crew','Supprimer',`data-id="${crew.id}" data-departure="${departure.id}"`,'danger-button')}</div>`:''}</div></details>`;
}

export function renderCrews(event,departure){
  const manage=canManage()&&departure.startsAt>Date.now();const crews=[...(departure.crews||[])].sort((a,b)=>event.categories.indexOf(a.category)-event.categories.indexOf(b.category)||String(a.name).localeCompare(String(b.name),'fr',{sensitivity:'base',numeric:true}));const assigned=new Set(crews.flatMap(crew=>crew.registrationIds||[]));const unassigned=(departure.availability||[]).filter(reg=>reg.status!=='unavailable'&&!assigned.has(reg.id)).sort((a,b)=>event.categories.indexOf(a.category)-event.categories.indexOf(b.category)||String(a.name).localeCompare(String(b.name),'fr',{sensitivity:'base'}));
  return `<div class="crew-section"><div class="crew-heading"><div><h2>Équipages</h2></div></div>${crews.length?`<div class="crew-list">${crews.map((crew,index)=>managementCard(event,departure,crew,index,unassigned,manage)).join('')}</div>`:'<div class="empty">Aucun équipage créé sur ce départ pour le moment.</div>'}${manage&&unassigned.length?`<details class="ux-remaining-pilots-section">${contentSummary('Pilotes restants à affecter',pilotCount(unassigned))}<div class="ux-remaining-pilot-grid">${unassigned.map(reg=>remaining(event,departure,reg)).join('')}</div></details>`:''}</div>`;
}

export async function updateCrewState(select){
  const event=state.events.find(item=>item.id===state.currentEventId);const departure=event?.departures.find(item=>item.id===select.dataset.departure);const crew=departure?.crews.find(item=>item.id===select.dataset.crewId);if(!crew)throw Error('Équipage introuvable. Actualise la page.');const locked=select.value==='locked';if(locked===!!crew.locked)return;if(locked&&!confirm(`Marquer « ${crew.name} » comme équipage complet et verrouiller sa composition ?`)){select.value=crew.locked?'locked':'open';return;}select.disabled=true;try{await api(`/api/crews/${crew.id}`,'PATCH',{locked,version:crew.version});state.crewManagementOpen.add(crew.id);}finally{if(select.isConnected)select.disabled=false;}
}
