import {app,state,esc,eventTypeBadge,badge,circuitLabel,registrationCarLabel,renderAvailabilityTimeline,notifyRender} from './core.mjs';
const dateFormat=new Intl.DateTimeFormat('fr-FR',{timeZone:'Europe/Paris',weekday:'long',day:'numeric',month:'long',year:'numeric'});
function entryDate(d){try{return dateFormat.format(new Date(d.startsAt));}catch{return d.date||'';}}
function pSort(event){return(a,b)=>event.categories.indexOf(a.category)-event.categories.indexOf(b.category)||String(a.name).localeCompare(String(b.name),'fr',{sensitivity:'base'});}
function pilotCard(event,departure,reg,highlighted=false){return `<article class="pilot-row ux-my-entry-pilot-card${highlighted?' is-own-pilot':''}"><div class="pilot-main"><span class="pilot-name">${esc(reg.name)}</span><span class="pilot-car">${esc(registrationCarLabel(reg))}</span>${reg.preferredPilot?`<span class="pilot-preference">Souhaite rouler avec : <strong>${esc(reg.preferredPilot)}</strong></span>`:''}</div>${renderAvailabilityTimeline({departure,duration:event.durationHours||6,status:reg.status,label:`Disponibilités de ${reg.name}`})}</article>`;}
function summary(title,count){return `<summary class="ux-my-entry-accordion-summary"><span>${esc(title)}</span><strong>${count}</strong><span class="ux-my-entry-chevron" aria-hidden="true">›</span></summary>`;}
function card({event,departure,reg}){
  const crew=(departure.crews||[]).find(c=>(c.registrationIds||[]).includes(reg.id));const assigned=new Set((departure.crews||[]).flatMap(c=>c.registrationIds||[]));const unassigned=(departure.availability||[]).filter(p=>p.status!=='unavailable'&&!assigned.has(p.id)).sort(pSort(event));const members=crew?(crew.registrationIds||[]).map(id=>departure.availability.find(p=>p.id===id)).filter(Boolean):[];const otherCrews=(departure.crews||[]).filter(c=>c.id!==crew?.id);
  return `<details class="native-my-entry-card event-type-${event.eventType||'private'}"><summary class="native-my-entry-header"><span class="native-my-entry-toggle" aria-hidden="true">+</span><div class="native-my-entry-title">${reg.managed?`<strong class="ux-managed-entry-name">${esc(reg.name)}</strong>`:''}<span class="ux-my-entry-departure">Départ ${esc(departure.time||'')}</span><h2>${esc(event.name)}</h2><span class="ux-my-entry-date">${esc(entryDate(departure))}</span><div class="native-my-entry-meta">${eventTypeBadge(event.eventType)}${badge(reg.category)}<span>${esc(circuitLabel(event.circuit))}</span><span>${event.durationHours||6} h</span></div></div><button type="button" class="primary-button native-my-entry-open-event" data-action="open" data-id="${event.id}" data-departure="${departure.id}">Voir l’événement complet</button></summary><div class="native-my-entry-body"><details class="ux-my-entry-content-accordion">${summary('Mon équipage',members.length)}<div class="ux-my-entry-content-body">${crew?`<article class="ux-my-own-crew"><header class="ux-my-own-crew-head"><div class="ux-my-own-crew-identity"><div><strong>${esc(crew.name)}</strong><span>${esc(crew.car||'Voiture à définir')}</span></div></div><span class="ux-my-crew-state">${crew.locked?'Équipage complet':'Équipage ouvert'}</span></header><div class="ux-my-pilot-grid">${members.map(p=>pilotCard(event,departure,p,p.id===reg.id)).join('')}</div></article>`:`<article class="ux-my-awaiting-crew"><div class="ux-my-awaiting-copy"><strong>En attente d’affectation</strong><span>Cette inscription n’est pas encore rattachée à un équipage.</span></div>${pilotCard(event,departure,reg,true)}</article>`}<section class="ux-my-other-crews"><div class="ux-my-other-crews-heading"><strong>Autres équipages</strong><span>${otherCrews.length}</span></div>${otherCrews.map(c=>`<article class="ux-my-other-crew"><strong>${esc(c.name)}</strong><span>${esc(c.car||'Voiture à définir')}</span></article>`).join('')||'<p class="muted">Aucun autre équipage sur ce départ.</p>'}</section></div></details><details class="ux-my-entry-content-accordion">${summary('Pilotes sans équipage',unassigned.length)}<div class="ux-my-entry-content-body"><div class="ux-my-pilot-grid">${unassigned.map(p=>pilotCard(event,departure,p,p.id===reg.id)).join('')||'<p class="empty">Tous les pilotes disponibles sont déjà affectés.</p>'}</div></div></details></div></details>`;
}
export function renderMyEntries(){state.page='my-entries';const entries=state.events.flatMap(event=>event.departures.flatMap(departure=>departure.availability.filter(reg=>reg.mine||reg.managed).map(reg=>({event,departure,reg}))));const section=(title,list)=>`<section class="native-my-entries-group"><div class="native-my-entries-group-heading"><h2>${title}</h2><span>${list.length} inscription${list.length>1?'s':''}</span></div>${list.length?`<div class="native-my-entry-list">${list.map(card).join('')}</div>`:'<p class="empty">Aucune inscription.</p>'}</section>`;app.innerHTML=`<div class="native-my-entries-heading"><span class="creation-kicker">ESPACE PILOTE</span><h1 class="page-title">MES INSCRIPTIONS</h1><p>Retrouve ici tes courses, ton équipage et les pilotes inscrits sur le même départ.</p></div>${section('Mes inscriptions personnelles',entries.filter(x=>x.reg.mine))}${entries.some(x=>x.reg.managed)?section('Inscriptions que je gère',entries.filter(x=>x.reg.managed)):''}`;notifyRender();}
