import {app,nav,state,esc,button,canManage,eventTypeBadge,eventBadge,eventCategoryCount,circuitVisual,dateLabel,countdown,groupEvents,notifyRender,notifyNav} from './core.mjs';

const dateFormatter=new Intl.DateTimeFormat('fr-FR',{timeZone:'Europe/Paris',day:'numeric',month:'long',year:'numeric'});
function dateParts(timestamp){const values={};for(const part of dateFormatter.formatToParts(new Date(timestamp)))if(part.type!=='literal')values[part.type]=part.value;return values;}
function dateRange(departures=[]){const dated=departures.filter(d=>Number.isFinite(Number(d.startsAt))).sort((a,b)=>Number(a.startsAt)-Number(b.startsAt));if(!dated.length)return'Dates à confirmer';const unique=[],seen=new Set();for(const d of dated){const item=dateParts(Number(d.startsAt)),key=`${item.year}-${item.month}-${item.day}`;if(!seen.has(key)){seen.add(key);unique.push(item);}}const first=unique[0],last=unique.at(-1);if(unique.length===1)return`${first.day} ${first.month} ${first.year}`;if(first.month===last.month&&first.year===last.year)return`${first.day}–${last.day} ${first.month} ${first.year}`;if(first.year===last.year)return`${first.day} ${first.month} – ${last.day} ${last.month} ${first.year}`;return`${first.day} ${first.month} ${first.year} – ${last.day} ${last.month} ${last.year}`;}
function displayTime(value){const match=String(value||'').match(/^(\d{1,2}):(\d{2})$/);if(!match)return String(value||'').trim();return match[2]==='00'?`${Number(match[1])}h`:`${Number(match[1])}h${match[2]}`;}
function scheduleLabel(event){const dates=dateRange(event.departures||[]),times=[...new Set((event.departures||[]).map(d=>displayTime(d.time)).filter(Boolean))];return times.length?`${dates} · ${times.slice(0,4).join(' • ')}${times.length>4?' • …':''}`:dates;}

export function renderNav(){nav.innerHTML=`${button('home','Événements')}${button('my-entries','Mes inscriptions')}<div class="nav-game-switcher" aria-label="Changer de simulateur"><a class="nav-game-switcher-button nav-game-switcher-lmu" href="/lmu/">Le Mans Ultimate</a><a class="nav-game-switcher-button nav-game-switcher-iracing" href="/iracing/">iRacing</a></div>`;notifyNav();}
export function showRecoveryLink(){if(!state.recoveryLink)return;app.insertAdjacentHTML('afterbegin',`<section class="recovery-panel"><label for="personalLink">Ton lien personnel pour retrouver et modifier tes inscriptions sans compte</label><input id="personalLink" readonly value="${esc(state.recoveryLink)}"><p>Conserve ce lien et garde-le privé.</p>${button('copy-link','Copier le lien')}${button('hide-link','Masquer')}</section>`);}
function eventCard({event,next,running,archived,end}){const untilNext=next?next.startsAt-Date.now():Infinity,statusClass=archived?'finished':running?'running':next&&untilNext<=3600000?'soon':'upcoming';return `<button class="event-card event-card-harmonized event-type-${event.eventType||'private'} ${archived?'archived':''}" data-action="open" data-id="${event.id}"><span class="event-card-body"><span class="event-card-title-row"><span class="event-name">${esc(event.name)}</span><span class="event-info">${eventTypeBadge(event.eventType)} <span class="event-home-schedule">${esc(scheduleLabel(event))}</span></span></span>${circuitVisual(event.circuit,true)}<span class="event-category-badges">${event.categories.map(category=>eventBadge(category,eventCategoryCount(event,category))).join('')}</span><span class="event-card-status">${running?'<span class="event-countdown event-countdown-primary running">COURSE EN COURS</span>':''}<span class="event-countdown ${statusClass}" ${next&&!archived?`data-status-time="${next.startsAt}"`:''}>${next?`Prochain départ : ${esc(dateLabel(next))} à ${esc(next.time)} · <span data-countdown="${next.startsAt}">${countdown(next.startsAt)}</span>`:archived?`Terminé le ${esc(dateLabel({startsAt:end}))}`:running?'':'Dates à confirmer'}</span></span></span></button>`;}
export function renderHome(message=''){state.page='home';state.currentEventId=null;state.editingEvent=null;state.drafts={};state.registrationOpen.clear();const groups=groupEvents(state.events,state.eventFilter);app.innerHTML=`<h1 class="page-title">ÉVÉNEMENTS</h1>${canManage()?`<div class="home-create-event">${button('create','Ajouter un évènement','','primary-button')}</div>`:''}${message?`<p class="creation-success" role="status">${esc(message)}</p>`:''}${!state.user?`<div class="toolbar home-toolbar">${button('guest-link','Mon lien personnel')}</div>`:''}<div class="event-filter" role="group" aria-label="Filtrer les événements">${button('event-filter','À venir',`data-filter="upcoming" aria-pressed="${state.eventFilter==='upcoming'}"`,'event-filter-button')}${button('event-filter','Archivés',`data-filter="archived" aria-pressed="${state.eventFilter==='archived'}"`,'event-filter-button')}</div>${groups.length?`<div class="event-agenda">${groups.map(group=>`<section class="event-period" aria-labelledby="period-${group.key}"><h2 class="event-period-heading" id="period-${group.key}"><span>${esc(group.label)}</span><small>${group.items.length} événement${group.items.length>1?'s':''}</small></h2><div class="event-list">${group.items.map(eventCard).join('')}</div></section>`).join('')}</div>`:`<div class="empty">${state.eventFilter==='upcoming'?'Aucun événement à venir.':'Aucun événement archivé.'}</div>`}`;showRecoveryLink();notifyRender();}
