<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>EnduranceManager.Plugin</AssemblyName>
    <SimHubDirectory Condition="'$(SimHubDirectory)' == ''">C:\Program Files (x86)\SimHub</SimHubDirectory>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="GameReaderCommon"><HintPath>$(SimHubDirectory)\GameReaderCommon.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="SimHub.Plugins"><HintPath>$(SimHubDirectory)\SimHub.Plugins.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Newtonsoft.Json"><HintPath>$(SimHubDirectory)\Newtonsoft.Json.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="System.Net.Http" />
  </ItemGroup>
</Project>
