import {getLocale,translateTextForLocale} from './i18n.mjs';

const EN=new Map(Object.entries({
  // Crew builder
  'FORMATION D’ÉQUIPAGE':'CREW SETUP','Aucun départ disponible':'No start available','Ce départ est déjà passé.':'This start has already passed.',
  'Inscription nécessaire':'Entry required','Inscris-toi d’abord sur ce départ pour pouvoir créer ton équipage.':'Register for this start before creating your crew.',
  'Créer un nouvel équipage':'Create a new crew','Annuler':'Cancel','Équipage':'Crew','Départ':'Start','Nom de l’équipage':'Crew name','Voiture':'Car','Composition':'Lineup',
  'Modifie le nom, la voiture et la composition. Les organisateurs gardent toujours un droit de supervision.':'Edit the name, car and lineup. Organizers always retain supervisory access.',
  'Crée l’équipage sur ce départ puis choisis les pilotes déjà inscrits.':'Create the crew for this start, then select drivers who are already registered.',
  'Tu deviens responsable de l’équipage et tu y es ajouté automatiquement.':'You become the crew owner and are added automatically.',
  'Cet équipage est marqué complet. Rouvre-le depuis sa carte avant de modifier sa composition.':'This crew is marked complete. Reopen it from its card before changing the lineup.',
  'Pour changer de catégorie, retire d’abord tous les pilotes de cet équipage.':'To change category, first remove every driver from this crew.',
  'Coche ou décoche les pilotes que tu veux dans cet équipage.':'Select or deselect the drivers you want in this crew.',
  'Tu peux ajouter dès maintenant d’autres pilotes inscrits dans la même catégorie.':'You can add other drivers already registered in the same category now.',
  'Aucun pilote disponible dans cette catégorie pour ce départ.':'No driver is available in this category for this start.',
  'Un pilote ne peut appartenir qu’à un équipage sur un même départ. Son affectation remplace ses autres inscriptions de catégorie sur ce départ.':'A driver can belong to only one crew for a given start. Assigning them to a crew replaces their other category entries for that start.',
  'Les inscriptions des pilotes restent conservées lorsqu’ils quittent un équipage.':'Driver entries are kept when they leave a crew.',
  'COUVERTURE PRÉVUE':'EXPECTED COVERAGE','Aucun pilote sélectionné.':'No driver selected.','Toutes les heures de course sont couvertes par la sélection actuelle.':'The current selection covers every race hour.',
  'Couverture prévue de l’équipage':'Expected crew coverage','Responsable de l’équipage':'Crew owner','Coéquipier souhaité :':'Preferred teammate:','aucune préférence':'no preference',
  'Événement introuvable. Actualise la page.':'Event not found. Refresh the page.','Connecte-toi avec Discord pour gérer un équipage.':'Sign in with Discord to manage a crew.',
  'Tu n’es pas responsable de cet équipage.':'You are not the owner of this crew.','Ce départ est passé. L’équipage est verrouillé.':'This start has passed. The crew is locked.',
  'Tous les départs de cet événement sont déjà passés.':'All starts for this event have already passed.','Inscris-toi d’abord sur ce départ avant de créer ton équipage.':'Register for this start before creating your crew.',
  'Impossible d’ouvrir l’éditeur d’équipage.':'Unable to open the crew editor.','L’équipage a été créé mais doit être actualisé avant d’y ajouter les autres pilotes.':'The crew was created but must be refreshed before other drivers can be added.',
  'Indique le nom de l’équipage.':'Enter the crew name.',

  // Help permission lists
  'consulter les événements, pilotes et équipages ;':'browse events, drivers and crews;','t’inscrire à un départ et, si tu es connecté, inscrire un autre pilote ;':'register for a start and, when signed in, register another driver;','indiquer et modifier tes disponibilités et préférences ;':'set and edit your availability and preferences;','créer ton propre équipage après ton inscription ;':'create your own crew after registering;','rejoindre ou quitter un équipage ouvert compatible ;':'join or leave a compatible open crew;','gérer l’équipage dont tu es responsable.':'manage the crew you own.',
  'créer ou modifier une course ;':'create or edit a race;','modifier un équipage dont tu n’es pas responsable ;':'edit a crew you do not own;','gérer les rôles des membres ;':'manage member roles;','supprimer un événement.':'delete an event.',
  'faire tout ce qu’un pilote peut faire ;':'do everything a driver can do;','créer et modifier les événements ;':'create and edit events;','inscrire un autre pilote et modifier les inscriptions ;':'register another driver and edit entries;','créer et gérer tous les équipages ;':'create and manage all crews;','affecter ou retirer des pilotes ;':'assign or remove drivers;','choisir la voiture et le statut des équipages ;':'choose crew cars and status;','contrôler la couverture de la course.':'check race coverage.',
  'attribuer ou retirer les rôles des membres ;':'assign or remove member roles;','accéder aux fonctions réservées à l’administrateur principal ;':'access functions reserved for the primary administrator;','supprimer définitivement un événement.':'permanently delete an event.',
  'Accéder à':'Open','Attribuer ou retirer le rôle':'Assign or remove the','Conserver le contrôle des droits du site.':'Retain control of site permissions.','Supprimer définitivement un événement.':'Permanently delete an event.',

  // Privacy policy
  '1. À quoi sert Endurance Manager ?':'1. What is Endurance Manager for?','2. Données traitées':'2. Data processed','3. Pourquoi ces données sont-elles utilisées ?':'3. Why is this data used?','4. Cookies et accès':'4. Cookies and access','5. Durée de conservation':'5. Retention periods','6. Prestataires utilisés':'6. Service providers','7. Tes droits':'7. Your rights','8. Sécurité':'8. Security','9. Évolution de cette politique':'9. Changes to this policy',
  'Endurance Manager est un outil d’organisation de courses d’endurance simracing. Les données traitées servent uniquement à gérer les comptes, les inscriptions, les disponibilités des pilotes, les équipages, les rôles d’organisation et la sécurité du service.':'Endurance Manager is a tool for organizing sim-racing endurance events. Data is processed only to manage accounts, entries, driver availability, crews, organizer roles and service security.',
  'Les responsables du traitement sont Nathan Boulanger et Raphaël Nagel, cofondateurs et responsables d’Endurance Manager. Pour toute question ou demande concernant tes données, contacte les responsables par le moyen de contact habituel communiqué au sein de ta communauté Endurance Manager.':'The data controllers are Nathan Boulanger and Raphaël Nagel, co-founders and operators of Endurance Manager. For any question or request concerning your data, contact them through the usual contact channel provided within your Endurance Manager community.',
  'Selon la façon dont tu utilises le site, Endurance Manager peut traiter :':'Depending on how you use the site, Endurance Manager may process:',
  'ton pseudo et les informations liées à tes inscriptions ;':'your driver name and information related to your entries;','tes disponibilités, catégorie, préférences de voiture et éventuel pilote souhaité ;':'your availability, category, car preferences and any preferred teammate;','ton appartenance à un équipage et les informations nécessaires à son organisation ;':'your crew membership and information needed to organize it;','des données techniques strictement nécessaires à la connexion, à la récupération d’un accès invité et à la protection contre les abus.':'technical data strictly necessary for sign-in, guest-access recovery and abuse prevention.',
  'si tu te connectes avec Discord : ton identifiant Discord et ton nom d’affichage. Endurance Manager demande uniquement l’autorisation Discord':'if you sign in with Discord: your Discord ID and display name. Endurance Manager requests only the Discord','afin de t’authentifier et de t’identifier ; le site ne demande ni ton adresse e-mail, ni le contenu de tes messages Discord, ni l’accès à tes conversations ;':'permission to authenticate and identify you; the site does not request your email address, the content of your Discord messages or access to your conversations;',
  'Elles sont utilisées pour fournir les fonctions demandées par les utilisateurs : afficher les événements, enregistrer et retrouver les inscriptions, identifier les pilotes, constituer les équipages, appliquer les droits organisateur/administrateur et sécuriser les accès.':'This data is used to provide requested features: display events, save and retrieve entries, identify drivers, form crews, apply organizer/administrator permissions and secure access.',
  'Ces traitements reposent sur le fonctionnement du service demandé par l’utilisateur et sur l’intérêt légitime des responsables à organiser les événements et à protéger le service.':'This processing is based on providing the service requested by the user and on the controllers’ legitimate interest in organizing events and protecting the service.',
  'Endurance Manager utilise uniquement des cookies nécessaires au fonctionnement du service :':'Endurance Manager uses only cookies required for the service to operate:',
  ': session de connexion, valable jusqu’à 7 jours ;':': sign-in session, valid for up to 7 days;',': permet de retrouver un accès invité, valable jusqu’à 365 jours ;':': lets the service recover guest access, valid for up to 365 days;',': sécurise temporairement la connexion Discord, valable environ 10 minutes.':': temporarily secures Discord sign-in, valid for about 10 minutes.',
  // Privacy policy, 25 September 2026 additions
  'si tu te connectes avec Discord : l’identifiant de ton avatar Discord, pour l’afficher dans le menu de ton compte ;':'if you sign in with Discord: your Discord avatar identifier, to show it in your account menu;',
  'des données techniques strictement nécessaires à la connexion, à la récupération d’un accès invité et à la protection contre les abus ;':'technical data strictly needed for sign-in, guest access recovery and abuse protection;',
  'en cas d’erreur technique dans ton navigateur : la page concernée, le message d’erreur, le type de navigateur et la taille d’écran. Ces rapports ne contiennent ni ton identifiant ni ton pseudo ; ils sont consultables uniquement par les organisateurs et administrateurs, afin de corriger les problèmes.':'if a technical error happens in your browser: the page, the error message, the browser type and the screen size. These reports contain neither your identifier nor your driver name; only organizers and administrators can read them, to fix problems.',
  ': sécurise temporairement la connexion Discord, valable environ 10 minutes ;':': temporarily secures the Discord sign-in, valid for about 10 minutes;',
  ': retient la page à rouvrir après la connexion Discord (par exemple la course que tu consultais), valable environ 10 minutes ;':': remembers the page to reopen after the Discord sign-in (for example the race you were viewing), valid for about 10 minutes;',
  ': identifiant de ton avatar Discord pour l’afficher dans le menu du compte, valable jusqu’à 7 jours.':': your Discord avatar identifier, to show it in the account menu, valid for up to 7 days.',
  '; ceux qui touchent à la connexion (':'; those related to sign-in (',') sont aussi':') are also',', donc inaccessibles aux scripts de la page. Le cookie d’avatar ne contient aucune donnée de connexion.':', so page scripts cannot read them. The avatar cookie contains no sign-in data.',
  'Le navigateur garde aussi en mémoire locale, sur ton appareil uniquement, la langue choisie et le dernier pseudo utilisé pour t’inscrire, afin de préremplir le formulaire.':'Your browser also keeps in local storage, on your device only, the chosen language and the last driver name used to register, to prefill the form.',
  'Le code d’Endurance Manager ne dépose pas de cookie publicitaire ni de cookie d’analyse d’audience. Il n’y a donc pas de bannière de consentement publicitaire sur le site.':'Endurance Manager’s code sets no advertising or audience analytics cookie, so there is no advertising consent banner on the site.',
  'les données anti-abus sont organisées par périodes de 10 minutes et sont supprimées automatiquement, au plus tard dans le quart d’heure qui suit leur expiration ;':'abuse-protection data is grouped in 10-minute periods and deleted automatically, at the latest within fifteen minutes after it expires;',
  'les rapports d’erreur technique sont supprimés après 14 jours ;':'technical error reports are deleted after 14 days;',
  'Ces cookies sont configurés avec les protections':'These cookies use the protections','. Le code d’Endurance Manager ne dépose pas de cookie publicitaire ni de cookie d’analyse d’audience. Il n’y a donc pas de bannière de consentement publicitaire sur le site.':'. Endurance Manager does not set advertising or audience-analytics cookies. The site therefore does not display an advertising consent banner.',
  'les sessions de connexion expirent au plus tard après 7 jours ;':'sign-in sessions expire after no more than 7 days;','les données temporaires de connexion Discord expirent après environ 10 minutes ;':'temporary Discord sign-in data expires after about 10 minutes;','les données anti-abus sont organisées par périodes de 10 minutes et sont supprimées lors des opérations de nettoyage du service ;':'anti-abuse data is grouped into 10-minute periods and deleted during service cleanup operations;','le cookie d’accès invité peut être conservé jusqu’à 365 jours ;':'the guest-access cookie may be kept for up to 365 days;','les comptes, inscriptions et données d’organisation sont conservés pendant la durée nécessaire au fonctionnement du service, puis supprimés lorsqu’ils ne sont plus utiles ou à la suite d’une demande légitime d’effacement.':'accounts, entries and organization data are kept for as long as needed to operate the service, then deleted when no longer useful or following a legitimate deletion request.',
  'Le service s’appuie sur Cloudflare pour l’hébergement de l’application et de la base de données.':'The service uses Cloudflare to host the application and database.','Discord est utilisé uniquement comme fournisseur d’authentification et d’identification lorsque tu choisis de te connecter avec Discord. Endurance Manager utilise l’autorisation':'Discord is used only as an authentication and identification provider when you choose to sign in with Discord. Endurance Manager uses the','pour récupérer les informations minimales nécessaires à cette connexion.':'permission to retrieve the minimum information required for that sign-in.','Endurance Manager ne vend pas les données personnelles et ne les utilise pas à des fins publicitaires.':'Endurance Manager does not sell personal data or use it for advertising.',
  'Conformément au RGPD, tu peux notamment demander l’accès à tes données, leur rectification, leur effacement ou la limitation de leur traitement, et exercer un droit d’opposition lorsque celui-ci est applicable.':'Under the GDPR, you may request access to your data, correction, deletion or restriction of processing, and exercise a right to object where applicable.','Pour exercer ces droits, contacte les responsables d’Endurance Manager par le moyen de contact habituel communiqué au sein de ta communauté. Tu peux également saisir la CNIL si tu estimes que tes droits ne sont pas respectés.':'To exercise these rights, contact the Endurance Manager operators through the usual contact channel provided within your community. You may also contact the CNIL if you believe your rights are not being respected.',
  'Les jetons de session et d’accès sont stockés sous forme hachée côté serveur. Les cookies sensibles sont sécurisés, les réponses de l’API ne sont pas mises en cache, et les actions de gestion sont soumises à des contrôles de rôle et d’origine.':'Session and access tokens are stored as hashes on the server. Sensitive cookies are secured, API responses are not cached, and management actions are subject to role and origin checks.',
  'Cette page peut être mise à jour si les fonctions du site, les données traitées ou les prestataires utilisés évoluent. La date de mise à jour affichée en haut de la page permet d’identifier la version en vigueur.':'This page may be updated if site features, processed data or service providers change. The update date shown at the top identifies the current version.',

  // Legal information
  'Marques, jeux et absence d’affiliation':'Trademarks, games and no affiliation','Cofondateurs et responsables du site :':'Co-founders and site operators:','Édition :':'Publishing:','Contact :':'Contact:','Hébergement :':'Hosting:',
  'Endurance Manager est un projet communautaire de gestion d’événements de simracing, proposé gratuitement et sans activité commerciale liée au service.':'Endurance Manager is a community sim-racing event management project, provided free of charge with no commercial activity related to the service.',
  'site édité à titre non professionnel. Les coordonnées personnelles des responsables ne sont pas publiées sur le site.':'the site is published on a non-professional basis. The operators’ personal contact details are not published on the site.',
  'les utilisateurs du service peuvent joindre les responsables par le moyen de contact habituel communiqué au sein de leur communauté Endurance Manager.':'service users can contact the operators through the usual contact channel provided within their Endurance Manager community.',
  'Si Endurance Manager devient ultérieurement un service professionnel, payant ou exploité dans le cadre d’une entreprise, les présentes mentions devront être adaptées aux obligations applicables à cette activité.':'If Endurance Manager later becomes a professional, paid, or business-operated service, this legal notice will need to be updated to meet the applicable obligations.',
  'La structure, le code spécifique, les textes et les éléments graphiques originaux d’Endurance Manager sont protégés par les règles applicables à la propriété intellectuelle, sous réserve des droits détenus par leurs auteurs ou titulaires respectifs.':'Endurance Manager’s structure, specific code, texts and original graphic elements are protected by applicable intellectual-property rules, subject to rights held by their respective authors or owners.',
  'La reproduction, la redistribution ou la réutilisation substantielle d’éléments propres à Endurance Manager ne confère aucun droit sur les marques, logiciels, véhicules, circuits, championnats ou autres contenus appartenant à des tiers.':'Reproduction, redistribution or substantial reuse of Endurance Manager-specific material grants no rights over trademarks, software, vehicles, circuits, championships or other third-party content.',
  'Les cartes de circuits utilisées par le service proviennent désormais de sources libres documentées. Le détail des auteurs, fichiers sources et licences applicables est disponible sur la page':'The circuit maps used by the service now come from documented open sources. Details of authors, source files and applicable licences are available on the',
  'Endurance Manager est un outil communautaire indépendant. Il n’est ni affilié, ni sponsorisé, ni approuvé par Le Mans Ultimate, Studio 397, Motorsport Games, iRacing.com Motorsport Simulations, l’ACO, la FIA, l’IMSA ou les constructeurs et détenteurs de marques cités dans le service.':'Endurance Manager is an independent community tool. It is not affiliated with, sponsored by, or endorsed by Le Mans Ultimate, Studio 397, Motorsport Games, iRacing.com Motorsport Simulations, the ACO, FIA, IMSA, or any manufacturers or trademark owners mentioned in the service.',
  'Les noms « Le Mans Ultimate », « iRacing », les noms de voitures, de circuits, de championnats et les autres marques mentionnées appartiennent à leurs titulaires respectifs. Leur présence sert uniquement à identifier les simulateurs, catégories, véhicules ou circuits concernés par les événements organisés.':'The names “Le Mans Ultimate” and “iRacing”, as well as car, circuit, championship and other trademarks mentioned, belong to their respective owners. They are used only to identify the simulators, categories, vehicles or circuits relevant to organized events.',
  'Endurance Manager n’accorde aucune licence sur ces marques et ne prétend à aucun partenariat officiel avec leurs propriétaires.':'Endurance Manager grants no licence to these trademarks and claims no official partnership with their owners.',
  'Endurance Manager est fourni comme outil d’organisation communautaire. Les organisateurs restent responsables des informations qu’ils saisissent, des événements qu’ils créent et de la composition des équipages.':'Endurance Manager is provided as a community organization tool. Organizers remain responsible for the information they enter, the events they create and crew lineups.',
  'Le service peut évoluer, être interrompu ou modifié sans garantie de disponibilité permanente. Aucune fonctionnalité du site ne remplace les règlements officiels des compétitions ou des plateformes de simulation concernées.':'The service may change, be interrupted or modified without any guarantee of permanent availability. No site feature replaces the official rules of the relevant competitions or simulation platforms.',
  'Les informations relatives aux comptes, inscriptions, disponibilités, cookies nécessaires et droits des utilisateurs sont détaillées dans la':'Information about accounts, entries, availability, required cookies and user rights is detailed in the',

  // Circuit credits
  'Les fichiers ne sont pas revendiqués comme des créations d’Endurance Manager. Leur apparence est harmonisée à l’écran par des réglages de cadrage, de taille et de contraste propres à chaque circuit.':'The files are not claimed as Endurance Manager creations. Their on-screen appearance is harmonized using circuit-specific framing, size and contrast settings.',
  'Les licences ci-dessous sont celles indiquées sur les fiches Wikimedia Commons au moment de leur sélection. Le lien « source » donne accès au fichier, à son auteur, à son historique et aux conditions complètes de réutilisation.':'The licences below are those listed on Wikimedia Commons when the files were selected. The “source” link provides access to the file, its author, history and full reuse terms.',
  'Une même carte peut être utilisée dans les espaces LMU et iRacing lorsqu’ils partagent le même circuit. « Circuit à préciser » utilise uniquement le pictogramme générique original d’Endurance Manager. Les cartes de circuits ne constituent pas des logos officiels des simulateurs, championnats ou circuits.':'The same map may be used in LMU and iRacing when they share the same circuit. “Circuit to be confirmed” uses only Endurance Manager’s original generic icon. Circuit maps are not official logos of simulators, championships or circuits.'
}));

const PATTERNS=[
  [/^(\d+) h de course (?:ne sont|n’est) pas encore couverte(?:s)?\.$/u,([,n])=>`${n} race hour${n==='1'?'':'s'} ${n==='1'?'is':'are'} still not covered.`],
  [/^(\d+)\/(\d+) h couvertes$/u,([,covered,duration])=>`${covered}/${duration} h covered`],
  [/^(\d+) pilote(?:s)?$/u,([,n])=>`${n} driver${n==='1'?'':'s'}`],
  [/^Enregistrer l’équipage(?: · (\d+) pilote(?:s)?)?$/u,([,n])=>`Save crew${n?` · ${n} driver${n==='1'?'':'s'}`:''}`],
  [/^Créer l’équipage(?: · (\d+) pilote(?:s)?)?$/u,([,n])=>`Create crew${n?` · ${n} driver${n==='1'?'':'s'}`:''}`],
  [/^Gérer « (.+) »$/u,([,name])=>`Manage “${name}”`],
  [/^Équipage « (.+) » mis à jour\. (\d+) autre\(s\) inscription\(s\) du même départ ont été retirées\.$/u,([,name,n])=>`Crew “${name}” updated. ${n} other entr${n==='1'?'y was':'ies were'} removed from the same start.`],
  [/^Équipage « (.+) » créé\. (\d+) autre\(s\) inscription\(s\) du même départ ont été retirées\.$/u,([,name,n])=>`Crew “${name}” created. ${n} other entr${n==='1'?'y was':'ies were'} removed from the same start.`],
  [/^Équipage « (.+) » mis à jour\.$/u,([,name])=>`Crew “${name}” updated.`],
  [/^Équipage « (.+) » créé\.$/u,([,name])=>`Crew “${name}” created.`],
  [/^Impossible de (modifier|créer) cet équipage\.$/u,([,verb])=>`Unable to ${verb==='modifier'?'edit':'create'} this crew.`],
  [/^(.+) · départ (.+)$/u,([,date,time])=>`${date} · start ${time}`],
  [/^(.+) · (Administrateur|Organisateur|Pilote)$/u,([,name,role])=>`${name} · ${{Administrateur:'Administrator',Organisateur:'Organizer',Pilote:'Driver'}[role]}`],
  [/^(.*) — domaine public —$/u,([,prefix])=>`${prefix} — public domain —`]
];

function translateExtra(value,locale=getLocale()){
  const source=String(value??'');
  if(!source.trim())return source;
  const base=translateTextForLocale(source,locale);
  if(base!==source||locale!=='en')return base;
  const match=source.match(/^(\s*)([\s\S]*?)(\s*)$/u),leading=match?.[1]||'',core=match?.[2]||source,trailing=match?.[3]||'';
  if(EN.has(core))return`${leading}${EN.get(core)}${trailing}`;
  for(const[pattern,replacer]of PATTERNS){const found=core.match(pattern);if(found)return`${leading}${replacer(found)}${trailing}`;}
  return source;
}

export function translateExtendedTextForLocale(value,locale=getLocale()){return translateExtra(value,locale);}

const SKIP='[data-i18n-ignore],.account-name,.account-trigger-copy strong,.account-popover-profile strong,.event-name,.event-title,.native-my-entry-title h2,.pilot-name,.crew-summary-title strong,.crew-compact-team strong,.ux-my-own-crew-identity strong,.ux-my-other-crew-main strong,.ux-managed-entry-name,.hub-next-race h3,.members-identity strong,.crew-builder-pilot-head strong,script,style,code,pre,textarea';
function textNode(node,locale){const parent=node.parentElement;if(!parent||parent.closest(SKIP))return;const next=translateExtra(node.nodeValue,locale);if(next!==node.nodeValue)node.nodeValue=next;}
function attrs(element,locale){if(!(element instanceof Element)||element.closest(SKIP))return;for(const name of['aria-label','title','placeholder','alt']){if(!element.hasAttribute(name))continue;const current=element.getAttribute(name),next=translateExtra(current,locale);if(next!==current)element.setAttribute(name,next);}}
function tree(root,locale){if(!root)return;if(root.nodeType===Node.TEXT_NODE){textNode(root,locale);return;}if(root.nodeType!==Node.ELEMENT_NODE&&root.nodeType!==Node.DOCUMENT_NODE)return;if(root.nodeType===Node.ELEMENT_NODE)attrs(root,locale);const walker=document.createTreeWalker(root,NodeFilter.SHOW_ELEMENT|NodeFilter.SHOW_TEXT);let node=walker.nextNode();while(node){node.nodeType===Node.TEXT_NODE?textNode(node,locale):attrs(node,locale);node=walker.nextNode();}}
function init(){const locale=getLocale();if(locale!=='en')return;tree(document.body,locale);const observer=new MutationObserver(records=>{for(const record of records){if(record.type==='characterData')textNode(record.target,locale);else if(record.type==='attributes')attrs(record.target,locale);else for(const node of record.addedNodes)tree(node,locale);}});observer.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['aria-label','title','placeholder','alt']});}
if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();}
