import {nextSession} from '../shared/preparation.mjs';
const root=document.getElementById('preparation-app');
const crewId=new URL(location.href).searchParams.get('crew');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={worked:'Pratiqué',partial:'À compléter',todo:'À faire',unknown:'Sans données',optional:'Facultatif'};
let data,minutes=30,loading=false;
const path=`/api/crews/${encodeURIComponent(crewId||'')}/preparation`;
const clock=seconds=>{if(seconds==null)return '—';const ms=Math.round(seconds*1000);return `${Math.floor(ms/60000)}:${((ms%60000)/1000).toFixed(3).padStart(6,'0')}`;};
const elapsed=seconds=>seconds==null?'—':`${Math.floor(seconds/60)} min ${Math.floor(seconds%60).toString().padStart(2,'0')} s`;
const conditionLabel=c=>!c?'Conditions non mesurées':`${c.wet===true?'Mouillé':c.wet===false?'Sec':'Adhérence non mesurée'} · ${c.night===true?'Nuit':c.night===false?'Jour':'Lumière non mesurée'}`;
async function api(suffix='',method='GET',body){
  const response=await fetch(path+suffix,{method,credentials:'same-origin',cache:'no-store',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});
  const result=await response.json().catch(()=>({}));if(!response.ok)throw Error(result.error||'Action momentanément indisponible.');return result;
}
function message(text,error=false){const element=root.querySelector('[data-message]');if(element){element.className=`prep-message${error?' is-error':''}`;element.textContent=text;}}
function recommendation(){
  const next=nextSession(data.analysis,data.level,minutes);
  return `<div class="prep-briefing-line"><p class="prep-eyebrow">Prochaine séance</p><label><span class="sr-only">Temps disponible</span><select data-minutes>${[20,30,45,60].map(n=>`<option value="${n}"${n===minutes?' selected':''}>${n} min</option>`).join('')}</select></label></div><h2>${esc(next.title)}</h2><p>${esc(next.why)}</p><details class="prep-routine" data-section="routine"><summary>Ouvrir mon guide de séance <span aria-hidden="true">⌄</span></summary><p class="prep-goal"><strong>Objectif de la séance</strong>${esc(next.goal)}</p>${next.stintAdvice?`<p class="prep-stint-advice">${esc(next.stintAdvice)}</p>`:''}<div class="prep-guide">${next.phases.map((phase,i)=>`<details class="prep-phase" data-phase="${i}" data-section="phase-${phase.id}"${i===0?' open':' hidden'}><summary><span class="prep-phase-number">${i+1}</span><strong>${esc(phase.title)}</strong><span class="prep-phase-time">${phase.startMinute}–${phase.endMinute} min</span><span aria-hidden="true">⌄</span></summary><div><p class="prep-step-count">Étape ${i+1} sur ${next.phases.length}</p><ol>${phase.actions.map(action=>`<li>${esc(action)}</li>`).join('')}</ol><div class="prep-step-actions">${i?`<button class="link-button" type="button" data-next-phase="${i-1}">← Précédente</button>`:''}${i<next.phases.length-1?`<button class="secondary-button" type="button" data-next-phase="${i+1}">Étape suivante →</button>`:'<button class="secondary-button" type="button" data-show-data>Voir mon roulage</button>'}</div></div></details>`).join('')}</div><p class="prep-note">Ces durées servent de guide, sans chronomètre automatique. Termine le tour en cours avant de passer à la suite. Ouvrir une étape ne valide pas l’exercice.</p></details>`;
}
function topicMeasure(item){
  const a=data.analysis,known=data.analysis.total&&item.status!=='unknown';
  const values={familiarity:[a.total,data.level==='discover'?15:5,'tours enregistrés'],regularity:[a.paceSamples,10,'tours comparables'],stint:[a.longestSeconds/60,a.targetStintMinutes,'minutes en continu'],pits:[a.pitLaps,2,'tours avec passage aux stands'],wet:[a.wetSeconds/60,15,'minutes sur le mouillé'],night:[a.nightSeconds/60,15,'minutes de nuit']};
  if(!known)return '';
  const [value,target,unit]=values[item.key],ratio=Math.min(100,value/target*100);
  return `<div class="prep-topic-meter"><div><strong>${Math.floor(value)} / ${target}</strong><span>${unit}</span></div><meter min="0" max="${target}" value="${Math.min(target,value)}" aria-label="${esc(item.label)} : ${Math.floor(value)} sur ${target} ${unit}">${ratio.toFixed(0)} %</meter><p class="prep-note">Repère de pratique proposé, pas un seuil de compétence.</p></div>`;
}
function metricsMarkup(){
  const a=data.analysis,percent=a.validPercent==null?'—':a.validPercent.toFixed(1)+' %';
  const metric=(label,value,sub)=>`<div class="prep-metric"><span>${label}</span><strong>${value}</strong><small>${sub}</small></div>`;
  return `<section class="prep-relay-data"><div class="prep-progress-heading"><h2>Mes repères de relais</h2>${tip('relay-help','Le chrono médian et l’écart sont calculés sur le plus grand groupe de tours valides, sans stands ni interruption, dans une même séance et les mêmes catégories de conditions. La météo détaillée, l’usure des pneus, les contacts et le setup réellement utilisé ne sont pas mesurés.')}</div><div class="prep-metrics">${metric('Rythme de relais',clock(a.paceSeconds),a.paceSamples?`${a.paceSamples} tours comparables`:'En attente de tours comparables')}${metric('Écart médian',a.deviationSeconds==null?'—':a.deviationSeconds.toFixed(3)+' s','Écart au chrono médian')}${metric('Plus long relais',a.longestSeconds?elapsed(a.longestSeconds):'—',`Objectif équipage : ${a.targetStintMinutes} min`)}</div><details class="prep-details" data-section="data"><summary>Détail des données de roulage</summary><div><p class="prep-note">Groupe de référence : ${esc(conditionLabel(a.paceConditions))}${a.paceStartedAt?' · '+esc(new Date(a.paceStartedAt).toLocaleString('fr-FR')):''}. Les chronos du sec et du mouillé sont analysés séparément.</p><dl class="prep-data-list"><div><dt>Meilleur tour du groupe</dt><dd>${clock(a.bestSeconds)}</dd></div><div><dt>Tours valides identifiés</dt><dd>${a.knownValidity?`${a.valid} / ${a.knownValidity} · ${percent}`:'Non mesurés'}</dd></div><div><dt>Validité non renseignée</dt><dd>${a.unknownValidity} tour${a.unknownValidity===1?'':'s'}</dd></div><div><dt>Roulage enregistré</dt><dd>${elapsed(a.rollingSeconds)}</dd></div><div><dt>Carburant médian par tour</dt><dd>${a.fuelPerLap==null?'Non mesuré':a.fuelPerLap.toFixed(3)+' L · '+a.fuelSamples+' tours'}</dd></div><div><dt>Énergie virtuelle par tour</dt><dd>${a.energyPerLap==null?'Non mesurée':a.energyPerLap.toFixed(3)+' % · '+a.energySamples+' tours'}</dd></div><div><dt>Roulage sur le mouillé</dt><dd>${a.wetKnown?elapsed(a.wetSeconds):'Non mesuré'}</dd></div><div><dt>Roulage de nuit</dt><dd>${a.nightKnown?elapsed(a.nightSeconds):'Non mesuré'}</dd></div><div><dt>Tours avec passage aux stands</dt><dd>${a.total&&a.coverage.find(x=>x.key==='pits')?.status!=='unknown'?a.pitLaps:'Non mesuré'}</dd></div></dl><p class="prep-note">Les données absentes ne sont pas comptées comme un échec. Les consommations viennent du groupe de référence et ne constituent pas une stratégie de course.</p></div></details></section>`;
}
function stintHistory(){
  if(!data.sessions.some(s=>s.longestSeconds>0))return '';
  const target=data.analysis.targetStintMinutes*60,max=Math.max(target,...data.sessions.map(s=>s.longestSeconds));
  return `<div class="prep-stint-history"><h3>Relais enregistrés au fil des séances</h3><p class="prep-note">Plus longue séquence continue de chaque séance · objectif ${data.analysis.targetStintMinutes} min. La durée montre la pratique enregistrée, pas une progression de performance.</p><ul>${[...data.sessions].reverse().map(s=>`<li><span class="prep-stint-date">${esc(new Date(s.startedAt).toLocaleString('fr-FR',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}))}</span><div class="prep-stint-bar" role="img" aria-label="${s.longestSeconds?'Relais de '+elapsed(s.longestSeconds):'Relais non mesuré'}"><span class="${s.longestSeconds>=target?'worked':'partial'}" style="width:${s.longestSeconds/max*100}%"></span><i style="left:${target/max*100}%" aria-hidden="true"></i></div><strong>${s.longestSeconds?elapsed(s.longestSeconds):'Non mesuré'}</strong></li>`).join('')}</ul><p class="prep-note">Le trait indique le relais cible de l’équipage. Les pauses, stands et trous de collecte interrompent la séquence.</p></div>`;
}
function conditionOptions(value){return [[null,'À confirmer'],[false,'Non'],[true,'Oui']].map(([v,label])=>`<option value="${v===null?'unknown':String(v)}"${v===value?' selected':''}>${label}</option>`).join('');}
const TOPIC_HELP={
  familiarity:'Prendre des repères de freinage et une trajectoire confortable avec la voiture de course.',
  regularity:'Répéter une série de tours propres dans les mêmes conditions, plutôt que chercher un record.',
  stint:'Rouler sans pause ni retour au garage pour découvrir la voiture au fil d’un relais.',
  pits:'Répéter l’entrée, l’arrêt et la sortie des stands.',
  wet:'Pratiquer le freinage, la motricité et la visibilité sur une piste mouillée.',
  night:'Retrouver les repères et l’entrée des stands quand il fait nuit.'
};
function topicStatus(item){return data.analysis.total?item.status:item.status==='optional'?'optional':'unknown';}
function tip(id,text){return `<span class="prep-help"><button type="button" class="prep-help-button" data-help aria-label="Aide" aria-describedby="${id}" aria-expanded="false">?</button><span class="prep-tooltip" id="${id}" role="tooltip">${esc(text)}</span></span>`;}
function progressMarkup(){
  const items=data.analysis.coverage.filter(item=>!['wet','night'].includes(item.key)||data.conditions[item.key]===true||(item.key==='wet'?data.analysis.wetSeconds:data.analysis.nightSeconds)>0);
  return `<section class="prep-progress"><div class="prep-progress-heading"><h2>Ma préparation</h2>${tip('progress-help','Vert : pratiqué. Orange : à compléter. Rouge : à faire. Gris : données absentes. Ces repères montrent la pratique enregistrée, pas un niveau de maîtrise.')}</div><div class="prep-topics">${items.map(item=>{const status=topicStatus(item);return `<details class="prep-topic ${status}" data-section="topic-${item.key}"><summary><span class="prep-dot" aria-hidden="true">${status==='worked'?'✓':status==='todo'?'!':'•'}</span><strong>${esc(item.label)}</strong><span class="prep-status ${status}">${labels[status]}</span><span class="prep-chevron" aria-hidden="true">⌄</span></summary><div><p>${esc(TOPIC_HELP[item.key])}</p>${topicMeasure(item)}<p class="prep-observed"><span>Observation</span>${data.analysis.total?esc(item.evidence):'Aucune donnée reçue pour le moment.'}</p></div></details>`;}).join('')}</div></section>`;
}
function trainingMarkup(){
  return `<section class="prep-next" aria-label="Ta prochaine séance">${recommendation()}</section>
    ${progressMarkup()}
    <details class="prep-details" data-section="roulage"><summary>Mon roulage</summary><div>${data.analysis.total?`${metricsMarkup()}${stintHistory()}<h3>Dernières séances</h3>${data.sessions.map(s=>`<div class="prep-session"><span>${esc(new Date(s.startedAt).toLocaleString('fr-FR',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}))}</span><span>${s.minutes} min · ${s.total} tours</span></div>`).join('')}<p class="prep-note">Historique des 60 derniers jours, avec cette voiture et ce circuit.</p>`:'<p class="prep-empty">Aucune séance enregistrée. Le suivi automatique attend la validation du connecteur SimHub.</p>'}</div></details>
    <details class="prep-details" data-section="crew"><summary>Mon équipage</summary><div>${crewMarkup()}</div></details>
    <details class="prep-details" data-section="settings"><summary>Réglages</summary><div><label>Ta connaissance du circuit<select data-level><option value="discover"${data.level==='discover'?' selected':''}>Je découvre</option><option value="familiar"${data.level==='familiar'?' selected':''}>Je connais déjà</option></select></label><details class="prep-details" data-section="connection"><summary>Connexion SimHub · prototype</summary><div><p class="prep-note">Le connecteur doit être testé en jeu. Aucun installateur n’est disponible ; cette configuration sert aux tests et contient ta clé personnelle.</p><div class="prep-actions"><button class="secondary-button" data-device ${data.crew.car?'':'disabled'}>Configuration de test</button>${data.device.linked?'<button class="link-button" data-unlink>Retirer la liaison</button>':''}</div></div></details></div></details>`;
}
function crewMarkup(){
  const hasCar=Boolean(data.crew.car);
  const conditionText=key=>data.conditions[key]===true?'Prévu':data.conditions[key]===false?'Non prévu':'À confirmer';
  return `<section class="prep-card"><h2>Notre voiture</h2><p class="prep-car">${esc(data.crew.car||'Voiture à choisir dans l’équipage')}</p><div class="prep-setup">${data.setup?`<div><small>Setup commun</small><strong>${esc(data.setup.name)}</strong></div><a class="primary-button" href="${path}/setup">Télécharger le setup</a>`:'<p class="prep-muted">Le responsable peut ajouter ici le setup utilisé par tous les pilotes.</p>'}</div>${data.manage?`<label class="prep-upload">${data.setup?'Remplacer le setup':'Ajouter le setup'}<input type="file" accept=".svm,.sto" data-setup ${hasCar?'':'disabled'}></label><p class="prep-note">Fichier .svm ou .sto, 128 Ko maximum.</p>`:''}</section>
    <section class="prep-card"><h2>Conditions de course</h2><dl class="prep-conditions"><div><dt>Pluie</dt><dd>${conditionText('wet')}</dd></div><div><dt>Nuit</dt><dd>${conditionText('night')}</dd></div><div><dt>Relais à préparer</dt><dd>${data.conditions.stintMinutes} min</dd></div></dl>${data.manage?`<details class="prep-details" data-section="conditions"><summary>Modifier les conditions</summary><div><p class="prep-note">Ces choix adaptent la routine de tous les pilotes de l’équipage.</p><form data-conditions><div class="prep-fields"><label>Piste mouillée prévue<select name="wet">${conditionOptions(data.conditions.wet)}</select></label><label>Roulage de nuit prévu<select name="night">${conditionOptions(data.conditions.night)}</select></label><label class="prep-wide">Durée du relais en minutes<input name="stintMinutes" type="number" min="20" max="180" value="${data.conditions.stintMinutes}" required></label></div><button class="secondary-button" type="submit">Enregistrer</button></form></div></details>`:''}</section>
    <section class="prep-card"><h2>Nos entraînements</h2><ul class="prep-roster">${data.roster.map(p=>`<li><strong>${esc(p.name)}${p.mine?' · toi':''}</strong><span>${p.minutes?p.minutes+' min de roulage':'Aucune séance enregistrée'}</span></li>`).join('')}</ul></section>`;
}
function render(){
  const back=`/${data.event.game}/#event=${encodeURIComponent(data.event.id)}`;
  root.innerHTML=`<a class="prep-back" href="${back}">← Retour à la course</a><h1>Préparer la course</h1><p class="prep-subtitle">${esc(data.crew.name)} · ${esc(data.event.circuitName)}</p><p data-message role="status" class="prep-message"></p>${trainingMarkup()}`;
}
async function reload(){const open=[...root.querySelectorAll('details[open]:not([data-phase])')].map(e=>e.dataset.section);data=await api();render();for(const key of open){const detail=root.querySelector(`[data-section="${key}"]`);if(detail)detail.open=true;}}
async function action(run){if(loading)return;loading=true;try{await run();}catch(error){message(error.message,true);}finally{loading=false;}}
root.addEventListener('change',event=>{
  if(event.target.matches('[data-minutes]')){minutes=Number(event.target.value);const open=root.querySelector('[data-section="routine"]')?.open;root.querySelector('.prep-next').innerHTML=recommendation();root.querySelector('[data-section="routine"]').open=Boolean(open);return;}
  if(event.target.matches('[data-level]'))action(async()=>{await api('/profile','PATCH',{level:event.target.value});await reload();message('Parcours enregistré.');});
  if(event.target.matches('[data-setup]'))action(async()=>{
    const file=event.target.files[0];if(!file)return;
    if(file.size>128000)throw Error('Setup limité à 128 Ko.');
    const response=await fetch(path+'/setup',{method:'PUT',credentials:'same-origin',headers:{'Content-Type':'application/octet-stream','X-Setup-Name':file.name},body:file});
    if(!response.ok)throw Error((await response.json()).error||'Échec de l’envoi.');await reload();message('Setup commun enregistré.');
  });
});
root.addEventListener('submit',event=>{if(!event.target.matches('[data-conditions]'))return;event.preventDefault();const form=new FormData(event.target),flag=key=>form.get(key)==='unknown'?null:form.get(key)==='true';action(async()=>{await api('/conditions','PATCH',{wet:flag('wet'),night:flag('night'),stintMinutes:Number(form.get('stintMinutes'))});await reload();message('Conditions enregistrées.');});});
root.addEventListener('click',event=>{
  const help=event.target.closest('[data-help]');if(help){const open=help.getAttribute('aria-expanded')!=='true';help.setAttribute('aria-expanded',String(open));help.parentElement.classList.toggle('is-open',open);return;}
  for(const help of root.querySelectorAll('[data-help]')){help.setAttribute('aria-expanded','false');help.parentElement.classList.remove('is-open');}
  const nextPhase=event.target.closest('[data-next-phase]');if(nextPhase){const phase=root.querySelector(`[data-phase="${nextPhase.dataset.nextPhase}"]`);if(phase){for(const other of root.querySelectorAll('[data-phase]')){other.hidden=other!==phase;other.open=other===phase;}phase.querySelector('summary').focus();phase.scrollIntoView({block:'nearest',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}return;}
  if(event.target.closest('[data-show-data]')){const detail=root.querySelector('[data-section="data"]')||root.querySelector('[data-section="roulage"]');if(detail){root.querySelector('[data-section="roulage"]').open=true;detail.open=true;detail.querySelector('summary').focus();detail.scrollIntoView({block:'nearest',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}return;}
  if(event.target.closest('[data-device]'))action(async()=>{
    const config=await api('/device','POST'),blob=new Blob([JSON.stringify(config,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='EnduranceManager.connection.json';link.click();URL.revokeObjectURL(url);await reload();message('Configuration téléchargée. Elle contient ta clé personnelle : conserve-la sur ton PC.');
  });
  if(event.target.closest('[data-unlink]'))action(async()=>{await api('/device','DELETE');await reload();message('Liaison retirée.');});
});
root.addEventListener('keydown',event=>{if(event.key==='Escape')for(const help of root.querySelectorAll('[data-help]')){help.setAttribute('aria-expanded','false');help.parentElement.classList.remove('is-open');}});
if(crewId)reload().catch(error=>{root.innerHTML=`<h1>Préparation indisponible</h1><p>${esc(error.message)}</p><a class="secondary-button" href="/">Retour au site</a>`;});
else root.innerHTML='<h1>Choisis ton équipage</h1><p>Ouvre ta course puis « Ouvrir ma préparation ».</p><a class="secondary-button" href="/">Retour au site</a>';
