from pathlib import Path

app=Path('app.js')
s=app.read_text()
old_self='''        <section class="my-entry-section my-entry-self"><div class="my-entry-section-heading"><div><span class="my-entry-kicker">MON INSCRIPTION</span><h3>${esc(reg.name)}</h3></div><span class="my-entry-pill">${esc(reg.category)}</span></div>\n          <div class="my-entry-preferences"><div><span>Voiture(s) souhaitée(s)</span><strong>${esc(registrationCarLabel(reg))}</strong></div><div><span>Coéquipier souhaité</span><strong>${esc(reg.preferredPilot||'Aucune préférence')}</strong></div></div>${mineTimeline}\n        </section>\n'''
if old_self not in s: raise SystemExit('self block target not found')
s=s.replace(old_self,'',1)
s=s.replace('<span class="my-entry-kicker">MON ÉQUIPAGE</span>','<span class="my-entry-kicker">ÉQUIPAGE FAIT</span>',1)
start='''`:`<section class="my-entry-section my-entry-waiting"><span class="my-entry-kicker">ÉQUIPAGE</span><h3>${eventCrewCount?'En attente d’affectation':'Aucun équipage créé pour le moment'}</h3><p>${eventCrewCount?`${eventCrewCount} équipage${eventCrewCount>1?'s':''} existe${eventCrewCount>1?'nt':''} déjà sur ce départ, mais tu n’es pas encore affecté.`:'Ton inscription est bien enregistrée. Les organisateurs pourront former les équipages plus tard.'}</p>\n      <div class="my-entry-waiting-grid">\n        <div><h4>Pilotes sans équipage · ${esc(reg.category)}</h4><div class="my-entry-compact-pilots">${unassignedSameCategory.map(p=>`<span class="my-entry-compact-pilot ${p.id===reg.id?'is-me':''}"><strong>${esc(p.name)}${p.id===reg.id?' · Moi':''}</strong><small>${esc(registrationCarLabel(p))}${p.preferredPilot?` · souhaite ${esc(p.preferredPilot)}`:''}</small></span>`).join('')||'<p class="muted">Aucun pilote sans équipage dans ta catégorie.</p>'}</div></div>\n        <div><h4>Équipages existants · ${esc(reg.category)}</h4><div class="my-entry-existing-crews">${existingCrews.map(c=>{const names=(c.registrationIds||[]).map(id=>departure.availability.find(p=>p.id===id)?.name).filter(Boolean);return `<div class="my-entry-existing-crew"><strong>${esc(c.name)}</strong><span>${esc(c.car||'Voiture à définir')}</span><small>${names.length?esc(names.join(' · ')):'Aucun pilote affecté'}</small></div>`;}).join('')||'<p class="muted">Aucun équipage créé dans ta catégorie.</p>'}</div></div>\n      </div><p class="coverage-note">Ouvre l’événement complet pour consulter les disponibilités détaillées des autres pilotes et équipages.</p></section>`;'''
replacement='''`:`<section class="my-entry-section my-entry-waiting"><div class="my-entry-section-heading"><div><span class="my-entry-kicker">PILOTE EN AFFECTATION</span><h3>${esc(reg.name)}</h3></div><span class="my-entry-pill">${esc(reg.category)}</span></div>\n      <div class="my-entry-preferences"><div><span>Voiture(s) souhaitée(s)</span><strong>${esc(registrationCarLabel(reg))}</strong></div><div><span>Coéquipier souhaité</span><strong>${esc(reg.preferredPilot||'Aucune préférence')}</strong></div></div>${mineTimeline}\n      <p class="coverage-note">Ton équipage n’est pas encore validé.</p></section>`;'''
if start not in s: raise SystemExit('waiting block target not found')
s=s.replace(start,replacement,1)
old_pilots='''    const otherPilots=sameCategory.filter(p=>!crewRegs.some(c=>c.id===p.id));\n    const pilotsBlock=`<section class="my-entry-section my-entry-pilots-summary"><div class="my-entry-section-heading"><div><span class="my-entry-kicker">PILOTES SUR MON DÉPART</span><h3>${pilotCount(allAvailable)} pilote(s) inscrit(s)</h3></div><span class="my-entry-pill">${sameCategory.length} en ${esc(reg.category)}</span></div>\n      <div class="my-entry-compact-pilots">${otherPilots.map(p=>`<span class="my-entry-compact-pilot ${p.id===reg.id?'is-me':''}"><strong>${esc(p.name)}${p.id===reg.id?' · Moi':''}</strong><small>${esc(registrationCarLabel(p))}</small></span>`).join('')||'<p class="muted">Aucun autre pilote de ta catégorie hors de ton équipage.</p>'}</div>\n    </section>`;'''
new_pilots='''    const pilotsBlock=`<section class="my-entry-section my-entry-pilots-summary"><div class="my-entry-section-heading"><div><span class="my-entry-kicker">PILOTES EN AFFECTATION</span><h3>${unassignedSameCategory.length} pilote${unassignedSameCategory.length>1?'s':''} sans équipage</h3></div><span class="my-entry-pill">${esc(reg.category)}</span></div>\n      <div class="my-entry-compact-pilots">${unassignedSameCategory.map(p=>`<span class="my-entry-compact-pilot ${p.id===reg.id?'is-me':''}"><strong>${esc(p.name)}${p.id===reg.id?' · Moi':''}</strong><small>${esc(registrationCarLabel(p))}${p.preferredPilot?` · souhaite ${esc(p.preferredPilot)}`:''}</small></span>`).join('')||'<p class="muted">Tous les pilotes de ta catégorie sont déjà affectés à un équipage.</p>'}</div>\n      ${!crew?`<div class="my-entry-existing-crews-wrap"><h4>ÉQUIPAGES DÉJÀ FORMÉS</h4><div class="my-entry-existing-crews">${existingCrews.map(c=>{const names=(c.registrationIds||[]).map(id=>departure.availability.find(p=>p.id===id)?.name).filter(Boolean);return `<div class="my-entry-existing-crew"><strong>${esc(c.name)}</strong><span>${esc(c.car||'Voiture à définir')}</span><small>${names.length?esc(names.join(' · ')):'Aucun pilote affecté'}</small></div>`;}).join('')||'<p class="muted">Aucun équipage formé dans ta catégorie pour le moment.</p>'}</div></div>`:''}\n      <p class="coverage-note">Voir l’événement complet pour consulter les disponibilités détaillées des autres pilotes.</p>\n    </section>`;'''
if old_pilots not in s: raise SystemExit('pilots block target not found')
s=s.replace(old_pilots,new_pilots,1)
s=s.replace("    const allAvailable=departure.availability.filter(r=>r.status!=='unavailable');\n",'',1)
app.write_text(s)
css=Path('styles/application.css')
t=css.read_text()
if '.my-entry-existing-crews-wrap' not in t:
    t += '''\n\n/* Mes inscriptions: status-focused layout. */\n.my-entry-existing-crews-wrap { margin-top: 16px; padding-top: 14px; border-top: 1px solid var(--border); }\n.my-entry-existing-crews-wrap h4 { margin: 0 0 9px; color: var(--muted); font-size: 12px; font-weight: 900; letter-spacing: .7px; }\n'''
css.write_text(t)
idx=Path('index.html')
h=idx.read_text().replace('/styles.css?v=19-my-entries-course-accordion','/styles.css?v=20-my-entries-status').replace('/app.js?v=19-my-entries-course-accordion','/app.js?v=20-my-entries-status')
idx.write_text(h)
